version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 3000:3000

  express-server:
    container_name: express-server
    build:
      context: .
      dockerfile: prod.express.Dockerfile
    env_file:
     - .env
    restart: always
    ports:
      - 3001:3001

  db:
    image: matjpdh/lldb:1.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
