services:
  next-app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 3000:3000

  aspnetserver:
    image: matjpdh/ll-aspnet-server:latest
    restart: always    
    ports:
      - 7094:7094

  db:
    image: matjpdh/lldb:1.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
